package com.example.data

object TemplateProvider {
    fun getLandingPageHtml() = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nexus - Next Gen Platform</title>
    <link rel="stylesheet" href="style.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar">
        <div class="logo">Nexus<span>.</span></div>
        <ul class="nav-links">
            <li><a href="#home">Home</a></li>
            <li><a href="#features">Features</a></li>
            <li><a href="#pricing">Pricing</a></li>
        </ul>
        <button class="btn-primary">Get Started</button>
    </nav>

    <header id="home" class="hero">
        <div class="hero-content fade-in">
            <h1>Build The Future</h1>
            <p>Empower your business with our cutting-edge AI platform designed for scale and speed.</p>
            <div class="hero-btns">
                <button class="btn-primary large">Start Free Trial</button>
                <button class="btn-secondary large">Watch Demo <i class="fas fa-play"></i></button>
            </div>
        </div>
        <div class="hero-image slide-up">
            <div class="mockup-window">
                <div class="dots"><span></span><span></span><span></span></div>
                <div class="mockup-content">
                    <p>// Initialize Nexus Core</p>
                    <p>nexus.start({ mode: 'hyper' 
    fun getThreeJsHtml() = """

    fun getLandingPageCss() = """:root {
    --primary: #6366f1;
    --primary-hover: #4f46e5;
    --bg: #0f172a;
    --surface: #1e293b;
    --text: #f8fafc;
    --text-muted: #94a3b8;

    fun getThreeJsHtml() = """

    fun getLandingPageJs() = """// Scroll Reveal Animation
function reveal() {
    var reveals = document.querySelectorAll(".reveal");
    for (var i = 0; i < reveals.length; i++) {
        var windowHeight = window.innerHeight;
        var elementTop = reveals[i].getBoundingClientRect().top;
        var elementVisible = 100;
        if (elementTop < windowHeight - elementVisible) {
            reveals[i].classList.add("active");
        
    fun getThreeJsHtml() = """

    fun getTicTacToeHtml() = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tic-Tac-Toe Pro</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="glass-container">
        <h1>Tic-Tac-Toe</h1>
        <div class="mode-selector">
            <button id="btn-pvp" class="active">2 Players</button>
            <button id="btn-ai">vs AI</button>
        </div>
        <h2 id="status">Player X's turn</h2>
        <div class="board" id="board">
            <!-- cells generated by JS -->
        </div>
        <button id="reset" class="reset-btn">Reset Game</button>
    </div>
    <script src="main.js"></script>
</body>
</html>"""

    fun getTicTacToeCss() = """body {
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    margin: 0;
    background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%);
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    color: white;

    fun getThreeJsHtml() = """

    fun getTicTacToeJs() = """const board = document.getElementById('board');
const status = document.getElementById('status');
const resetBtn = document.getElementById('reset');
const btnPvp = document.getElementById('btn-pvp');
const btnAi = document.getElementById('btn-ai');

let cells = Array(9).fill(null);
let xIsNext = true;
let isAiMode = false;
let gameOver = false;

function init() {
    board.innerHTML = '';
    cells.forEach((_, i) => {
        const cell = document.createElement('div');
        cell.className = 'cell';
        cell.dataset.index = i;
        cell.addEventListener('click', () => handleMove(i));
        board.appendChild(cell);
    
    fun getThreeJsHtml() = """

    fun getKanbanHtml() = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pro Kanban Board</title>
    <link rel="stylesheet" href="style.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <h1><i class="fas fa-trello"></i> TaskFlow</h1>
    </header>
    
    <div class="board">
        <div class="column" id="todo" ondrop="drop(event)" ondragover="allowDrop(event)">
            <div class="col-header">
                <h2>To Do</h2>
                <span class="count" id="count-todo">0</span>
            </div>
            <div class="task-list" id="list-todo"></div>
            <div class="add-task">
                <input type="text" id="input-todo" placeholder="+ Add a card..." onkeypress="handleEnter(event, 'todo')">
            </div>
        </div>

        <div class="column" id="inprogress" ondrop="drop(event)" ondragover="allowDrop(event)">
            <div class="col-header">
                <h2>In Progress</h2>
                <span class="count" id="count-inprogress">0</span>
            </div>
            <div class="task-list" id="list-inprogress"></div>
            <div class="add-task">
                <input type="text" id="input-inprogress" placeholder="+ Add a card..." onkeypress="handleEnter(event, 'inprogress')">
            </div>
        </div>

        <div class="column" id="done" ondrop="drop(event)" ondragover="allowDrop(event)">
            <div class="col-header">
                <h2>Done</h2>
                <span class="count" id="count-done">0</span>
            </div>
            <div class="task-list" id="list-done"></div>
            <div class="add-task">
                <input type="text" id="input-done" placeholder="+ Add a card..." onkeypress="handleEnter(event, 'done')">
            </div>
        </div>
    </div>
    
    <script src="main.js"></script>
</body>
</html>"""

    fun getKanbanCss() = """:root {
    --bg-color: #0079bf;
    --col-bg: #ebecf0;
    --card-bg: #ffffff;
    --text-main: #172b4d;
    --text-muted: #5e6c84;

    fun getThreeJsHtml() = """

    fun getKanbanJs() = """let taskIdCounter = 1;

function allowDrop(ev) {
    ev.preventDefault();

    fun getThreeJsHtml() = """

    fun getThreeJsHtml() = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>Three.js Template</title>
    <style>
        body { margin: 0; overflow: hidden; background-color: #000; }
        canvas { display: block; }
        #info {
            position: absolute; top: 10px; width: 100%; text-align: center;
            color: white; font-family: sans-serif; pointer-events: none;
        }
    </style>
</head>
<body>
    <div id="info">Three.js - Rotating Cube</div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r134/three.min.js"></script>
    <script src="main.js"></script>
</body>
</html>"""

    fun getThreeJsJs() = """// Setup scene, camera, renderer
const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
const renderer = new THREE.WebGLRenderer({ antialias: true });
renderer.setSize(window.innerWidth, window.innerHeight);
document.body.appendChild(renderer.domElement);

// Create a cube
const geometry = new THREE.BoxGeometry();
// Use MeshNormalMaterial for cool colors without lighting
const material = new THREE.MeshNormalMaterial();
const cube = new THREE.Mesh(geometry, material);
scene.add(cube);

camera.position.z = 3;

// Handle window resize
window.addEventListener('resize', () => {
    renderer.setSize(window.innerWidth, window.innerHeight);
    camera.aspect = window.innerWidth / window.innerHeight;
    camera.updateProjectionMatrix();
});

// Animation loop
function animate() {
    requestAnimationFrame(animate);

    // Rotate cube
    cube.rotation.x += 0.01;
    cube.rotation.y += 0.01;

    renderer.render(scene, camera);
}

animate();
"""

    fun getPhaserHtml() = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Phaser Game</title>
    <script src="https://cdn.jsdelivr.net/npm/phaser@3.55.2/dist/phaser.min.js"></script>
    <style>
        body { margin: 0; padding: 0; background-color: #000; display: flex; justify-content: center; align-items: center; height: 100vh; }
        canvas { border: 1px solid #333; }
    </style>
</head>
<body>
    <script src="game.js"></script>
</body>
</html>"""

    fun getPhaserJs() = """const config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    physics: {
        default: 'arcade',
        arcade: { gravity: { y: 300 }, debug: false }
    },
    scene: { preload: preload, create: create, update: update }
};

const game = new Phaser.Game(config);

function preload() {
    // Generate placeholder textures programmatically
    let g = this.add.graphics();
    g.fillStyle(0x00ff00); g.fillRect(0,0,800,50); g.generateTexture('ground', 800, 50); g.clear();
    g.fillStyle(0xff0000); g.fillRect(0,0,32,32); g.generateTexture('player', 32, 32); g.clear();
    g.fillStyle(0xffff00); g.fillCircle(12,12,12); g.generateTexture('star', 24, 24); g.destroy();
}

let player, cursors;

function create() {
    this.add.text(16, 16, 'Phaser Game Engine', { fontSize: '32px', fill: '#fff' });

    let platforms = this.physics.add.staticGroup();
    platforms.create(400, 568, 'ground');

    player = this.physics.add.sprite(100, 450, 'player');
    player.setBounce(0.2);
    player.setCollideWorldBounds(true);

    this.physics.add.collider(player, platforms);
    
    cursors = this.input.keyboard.createCursorKeys();
    
    // Add touch support for mobile
    this.input.on('pointerdown', function(pointer) {
        if(player.body.touching.down) { player.setVelocityY(-330); }
    });
}

function update() {
    if (cursors.left.isDown) { player.setVelocityX(-160); }
    else if (cursors.right.isDown) { player.setVelocityX(160); }
    else { player.setVelocityX(0); }

    if (cursors.up.isDown && player.body.touching.down) {
        player.setVelocityY(-330);
    }
}
"""

}
